# summary.py
# Builds the summary comment that gets posted at the top of every PR.
# Gives reviewers a quick overview without having to scroll through
# every single inline comment to understand what was flagged.
#
# I added this after realising that inline comments alone aren't great
# for getting the big picture - you have to click through each one.
# A summary at the top makes the review much easier to digest.

def build_summary(files_reviewed, all_comments):
    """
    Takes the list of files we reviewed and all the comments we generated,
    and builds a nicely formatted markdown summary.
    """

    # count up how many of each severity we found
    error_count = 0
    warning_count = 0
    suggestion_count = 0

    for comment in all_comments:
        body = comment.get("body", "")
        if "Error" in body:
            error_count += 1
        elif "Warning" in body:
            warning_count += 1
        elif "Suggestion" in body:
            suggestion_count += 1

    total = error_count + warning_count + suggestion_count

    # pick a verdict line based on what we found
    if error_count > 0:
        verdict = "Found some issues that should be fixed before merging."
    elif warning_count > 0:
        verdict = "Mostly looks good, but a few things worth addressing."
    elif suggestion_count > 0:
        verdict = "Looks good overall — just a couple of minor suggestions."
    else:
        verdict = "No issues found. Looks clean! :white_check_mark:"

    lines = []
    lines.append("## AI Code Review Summary")
    lines.append("")
    lines.append(f"_{verdict}_")
    lines.append("")

    # show the breakdown if there were any issues
    if total > 0:
        lines.append("### What was found")
        lines.append("")

        if error_count > 0:
            plural = "error" if error_count == 1 else "errors"
            lines.append(f"- 🔴 **{error_count} {plural}** — should fix before merging")

        if warning_count > 0:
            plural = "warning" if warning_count == 1 else "warnings"
            lines.append(f"- 🟡 **{warning_count} {plural}** — worth looking at")

        if suggestion_count > 0:
            plural = "suggestion" if suggestion_count == 1 else "suggestions"
            lines.append(f"- 🔵 **{suggestion_count} {plural}** — optional improvements")

        lines.append("")

    # list which files were reviewed and how many issues each had
    if files_reviewed:
        lines.append("### Files reviewed")
        lines.append("")

        for filename in files_reviewed:
            # count comments for just this file
            file_issue_count = sum(
                1 for c in all_comments
                if c.get("path") == filename
            )

            if file_issue_count == 0:
                lines.append(f"- `{filename}` — no issues")
            elif file_issue_count == 1:
                lines.append(f"- `{filename}` — 1 issue")
            else:
                lines.append(f"- `{filename}` — {file_issue_count} issues")

        lines.append("")

    lines.append("---")
    lines.append("_Generated by [AI Code Reviewer](https://github.com/UmarN1/ai-code-reviewer) · Powered by Claude Sonnet_")

    return "\n".join(lines)
